version: '3.8'

services:
  backend:
    environment:
      - DNS_RESOLVER=127.0.0.11
    build: ./backend
    volumes:
      - ./backend/:/app  # Ensure the path is correct relative to docker-compose
    working_dir: /app/reax  # Ensure this matches the correct folder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    environment:
        - DNS_RESOLVER=127.0.0.11
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    command: postgres -c 'listen_addresses=*'
    image: postgres
    environment:
      DNS_RESOLVER: 127.0.0.11
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - app_network

  nginx:
    image: nginx
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  pgdata: